---
version: '3.8'

services:
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9003:9003"
      - "9093:9093"
    environment:
      - MINIO_ROOT_USER=ruoyi
      - MINIO_ROOT_PASSWORD=ruoyi123
    volumes:
      - minio_data:/data
      - minio_config:/root/.minio
    command: server /data --console-address ":9093" --address ":9003"
    restart: always
    networks:
      - minio-net

networks:
  minio-net:
    driver: bridge

volumes:
  minio_data:
  minio_config:
